
#ifndef LEDS_BIP_H_
#define LEDS_BIP_H_

#include "music.h"

const PROGMEM Music musicBip = 
{
    .bpm  = 144, 
    .size = 99,
    .data = 
    {
        {NOTE_E5, 4},
        {NOTE_B4, 8},
        {NOTE_C5, 8},
        {NOTE_D5, 4},
        {NOTE_C5, 8},
        {NOTE_B4, 8},
        {NOTE_A4, 4},
        {NOTE_A4, 8},
        {NOTE_C5, 8},
        {NOTE_E5, 4},
        {NOTE_D5, 8},
        {NOTE_C5, 8},
        {NOTE_B4, -4},
        {NOTE_C5, 8},
        {NOTE_D5, 4},
        {NOTE_E5, 4},
        {NOTE_C5, 4},
        {NOTE_A4, 4},
        {NOTE_A4, 8},
        {NOTE_A4, 4},
        {NOTE_B4, 8},
        {NOTE_C5, 8},
        {NOTE_D5, -4},
        {NOTE_F5, 8},
        {NOTE_A5, 4},
        {NOTE_G5, 8},
        {NOTE_F5, 8},
        {NOTE_E5, -4},
        {NOTE_C5, 8},
        {NOTE_E5, 4},
        {NOTE_D5, 8},
        {NOTE_C5, 8},
        {NOTE_B4, 4},
        {NOTE_B4, 8},
        {NOTE_C5, 8},
        {NOTE_D5, 4},
        {NOTE_E5, 4},
        {NOTE_C5, 4},
        {NOTE_A4, 4},
        {NOTE_A4, 4},
        {REST, 4},
        {NOTE_E5, 4},
        {NOTE_B4, 8},
        {NOTE_C5, 8},
        {NOTE_D5, 4},
        {NOTE_C5, 8},
        {NOTE_B4, 8},
        {NOTE_A4, 4},
        {NOTE_A4, 8},
        {NOTE_C5, 8},
        {NOTE_E5, 4},
        {NOTE_D5, 8},
        {NOTE_C5, 8},
        {NOTE_B4, -4},
        {NOTE_C5, 8},
        {NOTE_D5, 4},
        {NOTE_E5, 4},
        {NOTE_C5, 4},
        {NOTE_A4, 4},
        {NOTE_A4, 8},
        {NOTE_A4, 4},
        {NOTE_B4, 8},
        {NOTE_C5, 8},
        {NOTE_D5, -4},
        {NOTE_F5, 8},
        {NOTE_A5, 4},
        {NOTE_G5, 8},
        {NOTE_F5, 8},
        {NOTE_E5, -4},
        {NOTE_C5, 8},
        {NOTE_E5, 4},
        {NOTE_D5, 8},
        {NOTE_C5, 8},
        {NOTE_B4, 4},
        {NOTE_B4, 8},
        {NOTE_C5, 8},
        {NOTE_D5, 4},
        {NOTE_E5, 4},
        {NOTE_C5, 4},
        {NOTE_A4, 4},
        {NOTE_A4, 4},
        {REST, 4},
        {NOTE_E5, 2},
        {NOTE_C5, 2},
        {NOTE_D5, 2},
        {NOTE_B4, 2},
        {NOTE_C5, 2},
        {NOTE_A4, 2},
        {NOTE_GS4, 2},
        {NOTE_B4, 4},
        {REST, 8},
        {NOTE_E5, 2},
        {NOTE_C5, 2},
        {NOTE_D5, 2},
        {NOTE_B4, 2},
        {NOTE_C5, 4},
        {NOTE_E5, 4},
        {NOTE_A5, 2},
        {NOTE_GS5, 2},

    }
};

#endif
